name: Send Emails on Push

on:
  push:
    branches:
      - main 

jobs:
  send-emails:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          # Sender email (must allow SMTP)
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Code Pushed"
          to: "nawtest12@gmail.com"
          from: NawNaw <ting28418@gmail.com>
          body: "Hi, I just pushed my code to the repository. Please review."
          secure: true